name: ⁉️Bug
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: "Which Python version do you use? Please provide the full version."
      placeholder: "Python 3.9.7"
    validations:
      required: true  
  - type: input
    id: cuda_version
    attributes:
      label: Cuda Version
      description: "Please provide the details of your CUDA environment."
      placeholder: "CUDA 11.4, cuDNN 8.2"
    validations:
      required: true
  - type: input
    id: system_material
    attributes:
      label: System/Material
      description: "Please specify the system or material where the issue occurs."
      placeholder: "HfO2"
    validations:
      required: true
  - type: dropdown
    id: location
    attributes:
      label: Issue Type
      description: What type of issue are you encountering?
      options:
        - Code Issue
        - Compilation Issue
        - Other Errors (please specify in the description!)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
